version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "02:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
      - dependency-name: "symfony/*"
        versions: ["7.4.*"] # Ignore any attempts that would bump Symfony packages off version 7.4.
  groups:
    symfony:
      patterns:
      - "symfony/*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "02:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  groups:
    docker:
      patterns:
      - "docker/*"
    artifact:
      patterns:
      - "*-artifact"
