nelmio_api_doc:
    documentation:
        info:
            title: Ilios API Documentation
            description: This document provides instructions for connecting to the Ilios API for making requests to an
                Ilios backend from third-party applications.
            version: v3.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
