version: '3.8'
services:
  db:
    build:
      context: .
      target: mysql-demo
    ports:
      - "13306:3306"
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "8000:80"
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
    depends_on:
      - php
  php:
    build:
      context: .
      target: fpm-dev
    environment:
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=8.0
      - ILIOS_REQUIRE_SECURE_CONNECTION=false
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_SEARCH_HOSTS=opensearch:9200
      - ILIOS_REDIS_URL=redis://redis
      - ILIOS_FEATURE_DTO_CACHING=false
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/ilios-storage
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      # Remove the var/ directory from the bind-mount for better performance
      - /srv/app/var
      # Share the frontend files
      - ./var/frontend:/srv/app/var/frontend:rw,cached
      # Share storage between containers and make writes to the container authoritative with "delegated"
      - shared-storage:/ilios-storage:delegated
    depends_on:
      - db
      - redis
  messages:
    build:
      context: .
      target: consume-messages-dev
    environment:
      - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios?serverVersion=8.0
      - ILIOS_ERROR_CAPTURE_ENABLED=false
      - ILIOS_SEARCH_HOSTS=opensearch:9200
      - ILIOS_REDIS_URL=redis://redis
      - ILIOS_FILE_SYSTEM_STORAGE_PATH=/ilios-storage
    depends_on:
        - db
        - opensearch
        - redis
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      # Remove the var/ directory from the bind-mount for better performance
      - /srv/app/var
      # Share storage between containers and make writes to the container authoritative with "delegated"
      - shared-storage:/ilios-storage:delegated
  opensearch:
    build:
      context: .
      target: opensearch
    environment:
      - DISABLE_SECURITY_PLUGIN=true
      - discovery.type=single-node
    ports:
      - "9200:9200"
  redis:
    build:
      context: .
      target: redis
    ports:
      - "6379:6379"

volumes:
  shared-storage:
