version: '2'
services:
    db:
        image: iamjrjohnson/ilios-mysql-demo
        ports:
            - "17103:3306"
    php:
        image: iamjrjohnson/docker-ilios-php
        expose:
            - "9000"
        links:
            - db
        volumes:
            - ./:/ilios:ro
            - /ilios/var
            - /ilios/var/cache
            - /ilios/var/sessions
            - /ilios/var/tmp
            - ./var/logs:/ilios/var/logs:rw
    web:
        build: ./containers/nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes_from:
            - php