forge "https://forge.puppetlabs.com"

mod 'puppetlabs/apt', "1.7.0"
mod 'puppetlabs/stdlib', "4.4.0"
mod 'puppetlabs/mysql', "3.0.0"
mod 'puppetlabs/inifile', "1.2.0"
mod 'puppetlabs/concat', "1.1.2"
mod 'maestrodev/git', "1.0.6"
mod 'thias/fooacl', "1.0.0"
mod 'puppetlabs/apache', "1.2.0"
