Ilios\CoreBundle\Entity\CourseLearningMaterial:
    type: entity
    table: course_learning_material
    
    id:
        courseLearningMaterialId:
            type: integer
            unsigned: true
            id: true
            column: course_learning_material_id
            generator: { strategy: AUTO }
    fields:
        notes:
            type: text
            nullable: true
        required:
            type: boolean
        notesArePublic:
            type: boolean
            column: notes_are_public
    manyToOne:
        course:
            targetEntity: Course    
            joinColumns:
                course_id:
                    referencedColumnName: course_id    
        learningMaterial:
            targetEntity: LearningMaterial
            joinColumns:
                learning_material_id:
                    referencedColumnName: learning_material_id
#    manyToMany:
#        meshDescriptors:
#            targetEntity: MeshDescriptor
#            inversedBy: courseLearningMaterials
#            joinTable:
#                name: course_learning_material_x_mesh
#                joinColumns:
#                    course_learning_material_id:
#                        referencedColumnName: course_learning_material_id
#                inverseJoinColumns:
#                    mesh_descriptor_uid:
#                        referencedColumnName: mesh_descriptor_uid
