Ilios\CoreBundle\Entity\CurriculumInventoryInstitution:
    type: entity
    table: curriculum_inventory_institution
    id:
        schoolId:
            type: integer
            unsigned: true
            column: school_id
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 100
        aamcCode:
            type: string
            length: 10
            column: aamc_code
        addressStreet:
            type: string
            length: 100
            column: address_street
        addressCity:
            type: string
            length: 100
            column: address_city
        addressStateOrProvince:
            type: string
            length: 50
            column: address_state_or_province
        addressZipcode:
            type: string
            length: 10
            column: address_zipcode
        addressCountryCode:
            type: string
            length: 2
            fixed: true
            column: address_country_code
    oneToOne:
        school:
            targetEntity: School
            joinColumns:
                school_id:
                    referencedColumnName: school_id
