Ilios\CoreBundle\Entity\CurriculumInventorySequence:
    type: entity
    table: curriculum_inventory_sequence
    id:
        reportId:
            type: integer
            unsigned: true
            column: report_id
            id: true
            generator:
                strategy: NONE
    fields:
        description:
            type: text
            nullable: true
    oneToOne:
        report:
            targetEntity: CurriculumInventoryReport
            inversedBy: sequence
            joinColumns:
                report_id:
                    referencedColumnName: report_id
