Ilios\CoreBundle\Entity\CurriculumInventoryExport:
    type: entity
    table: curriculum_inventory_export
    indexes:
        fkey_curriculum_inventory_export_user_id:
            columns:
                - created_by
    id:
        reportId:
            type: integer
            unsigned: true
            column: report_id
            id: true
            generator:
                strategy: NONE
    fields:
        document:
            type: text
        createdOn:
            type: datetime
            default: CURRENT_TIMESTAMP
            column: created_on
    oneToOne:
        report:
            targetEntity: CurriculumInventoryReport
            inversedBy: export
            joinColumns:
                report_id:
                    referencedColumnName: report_id
    manyToOne:
        createdBy:
            targetEntity: User
            joinColumns:
                created_by:
                    referencedColumnName: user_id
