Ilios\CoreBundle\Entity\Group:
    type: entity
    table: group
    indexes:
        fkey_group_cohort_id:
            columns:
                - cohort_id
    id:
        groupId:
            type: integer
            unsigned: true
            id: true
            column: group_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 60
        instructors:
            type: string
            nullable: true
            length: 120
        location:
            type: string
            nullable: true
            length: 100
    manyToOne:
        cohort:
            targetEntity: Cohort
            joinColumns:
                cohort_id:
                    referencedColumnName: cohort_id
                    onDelete: CASCADE
        parents:
            targetEntity: Group
            joinColumns:
                parent_group_id:
                    referencedColumnName: group_id
    manyToMany:
        users:
            targetEntity: User
            inversedBy: userGroups
            joinTable:
                name: group_x_user
                joinColumns:
                    group_id:
                        referencedColumnName: group_id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id
        instructorUsers:
            targetEntity: User
            inversedBy: instructorUserGroups
            joinTable:
                name: group_x_instructor
                joinColumns:
                     group_id:
                        referencedColumnName: group_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id
                        onDelete: CASCADE
        instructorGroups:
            targetEntity: InstructorGroup
            inversedBy: groups
            joinTable:
                name: group_x_instructor_group
                joinColumns:
                    group_id:
                        referencedColumnName: group_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    instructor_group_id:
                        referencedColumnName: instructor_group_id
                        onDelete: CASCADE
        ilmSessionFacets:
            targetEntity: IlmSessionFacet
            mappedBy: groups
        offerings:
            targetEntity: Offering
            mappedBy: groups
