Ilios\CoreBundle\Entity\InstructorGroup:
    type: entity
    table: instructor_group
    id:
        instructorGroupId:
            type: integer
            unsigned: true
            id: true
            column: instructor_group_id    
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 60
        schoolId:
            type: integer
            unsigned: true
            column: school_id
    manyToMany:
        groups:
            targetEntity: Group
            mappedBy: instructorGroups
        ilmSessionFacets:
            targetEntity: IlmSessionFacet
            mappedBy: instructorGroups
        users:
            targetEntity: User
            inversedBy: instructorGroups
            joinTable:
                name: instructor_group_x_user
                joinColumns:
                    instructor_group_id:
                        referencedColumnName: instructor_group_id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id    
        offerings:
            targetEntity: Offering
            mappedBy: instructorGroups
