Ilios\CoreBundle\Entity\Offering:
    type: entity
    table: offering
    indexes:
        session_id_k:
            columns:
                - session_id
        offering_dates_session_k:
            columns:
                - offering_id
                - session_id
                - start_date
                - end_date
    id:
        offeringId:
            type: integer
            unsigned: true
            id: true
            column: offering_id    
            generator: { strategy: AUTO }
    fields:
        room:
            type: string
            length: 60
        startDate:
            type: datetime
            column: start_date
        endDate:
            type: datetime
            column: end_date
        deleted:
            type: boolean
        lastUpdatedOn:
            type: datetime
            default: CURRENT_TIMESTAMP
            column: last_updated_on
    manyToOne:
        session:
            targetEntity: Session    
            joinColumns:
                session_id:
                    referencedColumnName: session_id
        publishEvent:
            targetEntity: PublishEvent    
            joinColumns:
                publish_event_id:
                    referencedColumnName: publish_event_id   
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: offerings
            joinTable:
                name: offering_x_group
                joinColumns:
                    offering_id:
                        referencedColumnName: offering_id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: group_id    
        instructorGroups:
            targetEntity: InstructorGroup
            inversedBy: offerings
            joinTable:
                name: offering_x_instructor_group
                joinColumns:
                    offering_id:
                        referencedColumnName: offering_id
                inverseJoinColumns:
                    instructor_group_id:
                        referencedColumnName: instructor_group_id    
        users:
            targetEntity: User
            inversedBy: offerings
            joinTable:
                name: offering_x_learner
                joinColumns:
                    offering_id:
                        referencedColumnName: offering_id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id    
        reccuringEvents:
            targetEntity: RecurringEvent
            inversedBy: offerings
            joinTable:
                name: offering_x_recurring_event
                joinColumns:
                    offering_id:
                        referencedColumnName: offering_id
                inverseJoinColumns:
                    recurring_event_id:
                        referencedColumnName: recurring_event_id    
        instructorGroups:
            targetEntity: InstructorGroup
            inversedBy: offerings
            joinTable:
                name: offering_x_instructor_group
                joinColumns:
                    offering_id:
                        referencedColumnName: offering_id
                inverseJoinColumns:
                    instructor_group_id:
                        referencedColumnName: instructor_group_id    
