Ilios\CoreBundle\Entity\Report:
    type: entity
    table: report
    id:
        reportId:
            type: integer
            unsigned: true
            id: true
            column: report_id    
            generator: { strategy: AUTO }
    fields:
        creationDate:
            type: datetime
            column: creation_date
        subject:
            type: string
            length: 32
        prepositionalObject:
            type: string
            nullable: true
            length: 32
            column: prepositional_object
        deleted:
            type: boolean
        title:
            type: string
            nullable: true
            length: 240
    manyToOne:
        user:
            targetEntity: User
            inversedBy: reports
            joinColumns:
                user_id:
                    referencedColumnName: user_id
                    onDelete: cascade
