Ilios\CoreBundle\Entity\SessionType:
    type: entity
    table: session_type
    indexes:
        owning_school_id:
            columns:
                - owning_school_id
        assessment_option_fkey:
            columns:
                - assessment_option_id
    id:
        sessionTypeId:
            type: integer
            unsigned: true
            id: true
            column: session_type_id    
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        sessionTypeCssClass:
            type: string
            nullable: true
            length: 64
            column: session_type_css_class
        assessment:
            type: boolean
            default: '0'
    manyToOne:
        assessmentOption:
            targetEntity: AssessmentOption    
            joinColumns:
                assessment_option_id:
                    referencedColumnName: assessment_option_id    
        owningSchool:
            targetEntity: School    
            joinColumns:
                owning_school_id:
                    referencedColumnName: school_id    
    manyToMany:
        aamcMethods:
            targetEntity: AamcMethod
            inversedBy: sessionTypes
            joinTable:
                name: session_type_x_aamc_method
                joinColumns:
                    session_type_id:
                        referencedColumnName: session_type_id
                inverseJoinColumns:
                    method_id:
                        referencedColumnName: method_id
