Ilios\CoreBundle\Entity\UserSyncException:
    type: entity
    table: user_sync_exception
    indexes:
        user_id_fkey:
            columns:
                - user_id
    id:
        exceptionId:
            type: integer
            unsigned: true
            id: true
            column: exception_id    
            generator: { strategy: AUTO }
    fields:
        processId:
            type: integer
            unsigned: true
            column: process_id
        processName:
            type: string
            length: 100
            column: process_name
        exceptionCode:
            type: integer
            unsigned: true
            column: exception_code
        mismatchedPropertyName:
            type: string
            nullable: true
            length: 30
            column: mismatched_property_name
        mismatchedPropertyValue:
            type: string
            nullable: true
            length: 150
            column: mismatched_property_value
    manyToOne:
        user:
            targetEntity: User    
            joinColumns:
                user_id:
                    referencedColumnName: user_id       
                    onDelete: CASCADE
