Ilios\CoreBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: { message: "not.blank.first_name" }
            - Length:
                min: 1
                max: 30
                minMessage: length.min.first_name
                maxMessage: length.max.first_name
        lastName:
            - NotBlank: { message: "not.blank.last_name" }
            - Length:
                min: 1
                max: 20
                minMessage: length.min.last_name
                maxMessage: length.max.last_name
        middleName:
            - Length:
                min: 1
                max: 20
                minMessage: length.min.middle_name
                maxMessage: length.max.middle_name
        phone:
            - Length:
                min: 1
                max: 30
                minMessage: length.min.phone
                maxMessage: length.max.phone
        email:
            - NotBlank: { message: "not.blank.email" }
            - Email: { message: "not.valid.email" }
            - Length:
                max: 100
                maxMessage: length.max.email
        addedViaIlios:
            - Type:
                type: bool
                message: not.valid.added_via_ilios
        enabled:
            - Type:
                type: bool
                message: not.valid.enabled
        examined:
            - Type:
                type: bool
                message: not.valid.examined
        userSyncIgnore:
            - Type:
                type: bool
                message: not.valid.user_sync_ignore
        ucUid:
            - NotBlank: { message: "not.blank.uc_uid" }
            - Length:
                min: 9
                max: 9
                minMessage: length.min.uc_uid
                maxMessage: length.max.uc_uid
        otherId:
            - Length:
                min: 1
                max: 16
                minMessage: length.min.other_id
                maxMessage: length.max.other_id
        primarySchool:
            - NotBlank: { message: "not.blank.primary_school" }