Ilios\CoreBundle\Entity\User:
    exclusion_policy: ALL
    xml_root_name: user
    properties:
        userId:
            expose: true
            serialized_name: id
        firstName:
            expose: true
            serialized_name: firstName
        lastName:
            expose: true
            serialized_name: lastName
        middleName:
            expose: true
            serialized_name: middleName
        phone:
            expose: true
        email:
            expose: true
        enabled:
            expose: true
        ucUid:
            expose: true
            serialized_name: campusId
        otherId:
            expose: true
    virtual_properties:
        getPrimarySchoolId:
            serialized_name: primarySchool
            type: integer
        getOfferingIds:
            serialized_name: offerings
            type: array
