<?php

declare(strict_types=1);

namespace App\Tests\Service;

use App\Classes\Capabilities;
use App\Classes\UserRoles;
use App\Repository\SchoolRepository;
use App\Service\DefaultPermissionMatrix;
use App\Entity\DTO\SchoolDTO;
use App\Tests\TestCase;
use Mockery as m;

/**
 * Class DefaultPermissionMatrixTest
 * @package App\Tests\Service
 */
#[\PHPUnit\Framework\Attributes\CoversClass(\App\Service\DefaultPermissionMatrix::class)]
class DefaultPermissionMatrixTest extends TestCase
{
    protected DefaultPermissionMatrix $permissionMatrix;
    protected SchoolDTO $schoolDTO;

    public function setUp(): void
    {
        parent::setUp();
        $this->schoolDTO = new SchoolDTO(
            1,
            'School of Test',
            'sot',
            'admin@sot.edu',
            'alerts@sot.edu'
        );
        $schoolRepository = m::mock(SchoolRepository::class);
        $schoolRepository->shouldReceive('findDTOsBy')->andReturn([$this->schoolDTO]);
        $this->permissionMatrix = new DefaultPermissionMatrix($schoolRepository);
    }

    public function tearDown(): void
    {
        parent::tearDown();
        unset($this->schoolDTO);
        unset($this->permissionMatrix);
    }

    public static function hasPermissionProvider(): array
    {
        return [
            [
                Capabilities::CAN_UPDATE_SCHOOLS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_PROGRAMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_ALL_PROGRAMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_THEIR_PROGRAMS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_ALL_PROGRAMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_THEIR_PROGRAMS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_ALL_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_THEIR_PROGRAM_YEARS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_ALL_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_THEIR_PROGRAM_YEARS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UNLOCK_ALL_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UNLOCK_THEIR_PROGRAM_YEARS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_LOCK_ALL_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_LOCK_THEIR_PROGRAM_YEARS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_ARCHIVE_ALL_PROGRAM_YEARS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_ARCHIVE_THEIR_PROGRAM_YEARS,
                [
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_ALL_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_THEIR_COURSES,
                [
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_ALL_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_THEIR_COURSES,
                [
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UNLOCK_ALL_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UNLOCK_THEIR_COURSES,
                [
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_LOCK_ALL_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_LOCK_THEIR_COURSES,
                [
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_ARCHIVE_ALL_COURSES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_ARCHIVE_THEIR_COURSES,
                [
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_SESSIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_ALL_SESSIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_THEIR_SESSIONS,
                [
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_ALL_SESSIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_THEIR_SESSIONS,
                [
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_COMPETENCIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_COMPETENCIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_COMPETENCIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_SESSION_TYPES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_SESSION_TYPES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_SESSION_TYPES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_VOCABULARIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_VOCABULARIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_VOCABULARIES,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_TERMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_TERMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_TERMS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_INSTRUCTOR_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_INSTRUCTOR_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_INSTRUCTOR_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_LEARNER_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_LEARNER_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_LEARNER_GROUPS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_CURRICULUM_INVENTORY_REPORTS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_ALL_CURRICULUM_INVENTORY_REPORTS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_THEIR_CURRICULUM_INVENTORY_REPORTS,
                [
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_ALL_CURRICULUM_INVENTORY_REPORTS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_THEIR_CURRICULUM_INVENTORY_REPORTS,
                [
                ],
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_SCHOOL_CONFIGS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                    UserRoles::SCHOOL_DIRECTOR,
                ],
                [
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_CURRICULUM_INVENTORY_INSTITUTIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_CURRICULUM_INVENTORY_INSTITUTIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_CURRICULUM_INVENTORY_INSTITUTIONS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_CREATE_USERS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_UPDATE_USERS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
            [
                Capabilities::CAN_DELETE_USERS,
                [
                    UserRoles::SCHOOL_ADMINISTRATOR,
                ],
                [
                    UserRoles::SCHOOL_DIRECTOR,
                    UserRoles::PROGRAM_DIRECTOR,
                    UserRoles::PROGRAM_YEAR_DIRECTOR,
                    UserRoles::COURSE_ADMINISTRATOR,
                    UserRoles::COURSE_DIRECTOR,
                    UserRoles::COURSE_INSTRUCTOR,
                    UserRoles::SESSION_ADMINISTRATOR,
                    UserRoles::SESSION_INSTRUCTOR,
                    UserRoles::CURRICULUM_INVENTORY_REPORT_ADMINISTRATOR,
                ],
            ],
        ];
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('hasPermissionProvider')]
    public function testHasPermission(string $capability, array $allowedRoles, array $deniedRoles): void
    {
        $this->assertEquals(count($allowedRoles) +  count($deniedRoles), 10);
        foreach ($allowedRoles as $role) {
            $this->assertTrue(
                $this->permissionMatrix->hasPermission(
                    $this->schoolDTO->id,
                    $capability,
                    [ $role ]
                )
            );
        }

        foreach ($deniedRoles as $role) {
            $this->assertFalse(
                $this->permissionMatrix->hasPermission(
                    $this->schoolDTO->id,
                    $capability,
                    [ $role ]
                )
            );
        }
    }
}
