Ilios\CoreBundle\Entity\ApiKey:
    type: entity
    table: api_key
    uniqueConstraints:
        api_key_api_key:
            columns:
                - api_key
    id:
        userId:
            type: integer
            unsigned: true
            column: user_id
            id: true
            generator:
                strategy: NONE
                
    fields:
        apiKey:
            type: string
            length: 64
            column: api_key
    oneToOne:
        user:
            targetEntity: User
            inversedBy: apiKey
            joinColumns:
                user_id:
                    referencedColumnName: user_id
                    onDelete: cascade    
