Ilios\CoreBundle\Entity\AssessmentOption:
    type: entity
    table: assessment_option
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        assessmentOptionId:
            type: integer
            unsigned: true
            id: true
            column: assessment_option_id
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20
