Ilios\CoreBundle\Entity\AuditAtom:
    type: entity
    table: audit_atom
    indexes:
        idx_audit_atom_created_at:
            columns:
                - created_at
    id:
        auditAtomId:
            type: integer
            unsigned: true
            id: true
            column: audit_atom_id
            generator: { strategy: AUTO }
    fields:
        tableRowId:
            type: integer
            unsigned: true
            column: table_row_id
        tableColumn:
            type: string
            length: 50
            column: table_column
        tableName:
            type: string
            length: 50
            column: table_name
        eventType:
            type: boolean
            column: event_type
        createdAt:
            type: datetime
            default: CURRENT_TIMESTAMP
            column: created_at
    manyToOne:
        createdBy:
            targetEntity: User
            joinColumns:
                created_by:
                    referencedColumnName: user_id
