Ilios\CoreBundle\Entity\Cohort:
    type: entity
    table: cohort
    indexes:
        whole_k:
            columns:
                - program_year_id
                - cohort_id
                - title
        IDX_D3B8C16BCB2B0673:
            columns:
                - program_year_id
    id:
        cohortId:
            type: integer
            unsigned: true
            id: true
            column: cohort_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 60
    manyToOne:
        programYear:
            targetEntity: ProgramYear    
            joinColumns:
                program_year_id:
                    referencedColumnName: program_year_id
    manyToMany:
        courses:
            targetEntity: Course
            mappedBy: cohorts
