Ilios\CoreBundle\Entity\Competency:
    type: entity
    table: competency
    indexes:
        parent_competency_id_k:
            columns:
                - parent_competency_id
    id:
        competencyId:
            type: integer
            unsigned: true
            id: true
            column: competency_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            nullable: true
            length: 200
    manyToOne:
        parentCompetency:
            targetEntity: Competency
            joinColumns:
                parent_competency_id:
                    referencedColumnName: competency_id
        owningSchool:
            targetEntity: School    
            joinColumns:
                owning_school_id:
                    referencedColumnName: school_id
    manyToMany:
        pcrses:
            targetEntity: AamcPcrs
            inversedBy: competencies
            joinTable:
                name: competency_x_aamc_pcrs
                joinColumns:
                   competency_id:
                        referencedColumnName: competency_id
                inverseJoinColumns:
                    pcrs_id:
                        referencedColumnName: pcrs_id    
        programYears:
            targetEntity: ProgramYear
            mappedBy: competencies
