Ilios\CoreBundle\Entity\CourseClerkshipType:
    type: entity
    table: course_clerkship_type
    id:
        courseClerkshipTypeId:
            type: integer
            unsigned: false
            id: true
            column: course_clerkship_type_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 20
