Ilios\CoreBundle\Entity\Course:
    type: entity
    table: course
    indexes:
        title_course_k:
            columns:
                - course_id
                - title
        external_id:
            columns:
                - external_id
        clerkship_type_id:
            columns:
                - clerkship_type_id
    id:
        courseId:
            type: integer
            unsigned: true
            id: true
            column: course_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            nullable: true
            length: 200
        courseLevel:
            type: smallint
            unsigned: true
            column: course_level
        year:
            type: smallint
            unsigned: true
        startDate:
            type: date
            column: start_date
        endDate:
            type: date
            column: end_date
        deleted:
            type: boolean
        externalId:
            type: string
            nullable: true
            length: 18
            column: external_id
        locked:
            type: boolean
        archived:
            type: boolean
        publishedAsTbd:
            type: boolean
            column: published_as_tbd
    manyToOne:
        clerkshipType:
            targetEntity: CourseClerkshipType    
            joinColumns:
                clerkship_type_id:
                    referencedColumnName: course_clerkship_type_id
        owningSchool:
            targetEntity: School    
            joinColumns:
                owning_school_id:
                    referencedColumnName: school_id
        publishEvent:
            targetEntity: PublishEvent    
            joinColumns:
                publish_event_id:
                    referencedColumnName: publish_event_id
    manyToMany:
        directors:
            targetEntity: User
            inversedBy: directedCourses
            joinTable:
                name: course_director
                joinColumns:
                    course_id:
                        referencedColumnName: course_id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: user_id
        cohorts:
            targetEntity: Cohort
            inversedBy: courses
            joinTable:
                name: course_x_cohort
                joinColumns:
                    course_id:
                        referencedColumnName: course_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    cohort_id:
                        referencedColumnName: cohort_id
                        onDelete: CASCADE
        disciplines:
            targetEntity: Discipline
            inversedBy: courses
            joinTable:
                name: course_x_discipline
                joinColumns:
                    course_id:
                        referencedColumnName: course_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    discipline_id:
                        referencedColumnName: discipline_id
                        onDelete: CASCADE
        objectives:
            targetEntity: Objective
            inversedBy: courses
            joinTable:
                name: course_x_objective
                joinColumns:
                    course_id:
                        referencedColumnName: course_id
                        onDelete: CASCADE
                inverseJoinColumns:
                    objective_id:
                        referencedColumnName: objective_id
                        onDelete: CASCADE
#        meshDescriptors:
#            targetEntity: MeshDescriptor
#            inversedBy: courses
#            joinTable:
#                name: course_x_mesh
#                joinColumns:
#                    course_id:
#                        referencedColumnName: course_id
#                        onDelete: CASCADE
#                inverseJoinColumns:
#                    mesh_descriptor_uid:
#                        referencedColumnName: mesh_descriptor_uid
