Ilios\CoreBundle\Entity\CurriculumInventoryAcademicLevel:
    type: entity
    table: curriculum_inventory_academic_level
    indexes:
        IDX_B4D3296D4BD2A4C0:
            columns:
                - report_id
    uniqueConstraints:
        report_id_level:
            columns:
                - report_id
                - level
    id:
        academicLevelId:
            type: integer
            unsigned: true
            id: true
            column: academic_level_id
            generator: { strategy: AUTO }
    fields:
        level:
            type: integer
            unsigned: true
        name:
            type: string
            length: 50
        description:
            type: text
            nullable: true
    manyToOne:
        report:
            targetEntity: CurriculumInventoryReport    
            joinColumns:
                report_id:
                    referencedColumnName: report_id
