Ilios\CoreBundle\Entity\CurriculumInventorySequenceBlockSession:
    type: entity
    table: curriculum_inventory_sequence_block_session
    indexes:
        fkey_curriculum_inventory_sequence_block_session_session_id:
            columns:
                - session_id
        IDX_CF8E4F1261D1D223:
            columns:
                - sequence_block_id
    uniqueConstraints:
        report_session:
            columns:
                - sequence_block_id
                - session_id
    id:
        sequenceBlockSessionId:
            type: bigint
            unsigned: true
            id: true
            column: sequence_block_session_id
            generator: { strategy: AUTO }
    fields:
        countOfferingsOnce:
            type: boolean
            default: '1'
            column: count_offerings_once
    manyToOne:
        sequenceBlock:
            targetEntity: CurriculumInventorySequenceBlock
            joinColumns:
                sequence_block_id:
                    referencedColumnName: sequence_block_id
        session:
            targetEntity: Session
            joinColumns:
                session_id:
                    referencedColumnName: session_id
