Ilios\CoreBundle\Entity\Discipline:
    type: entity
    table: discipline
    id:
        disciplineId:
            type: integer
            unsigned: true
            id: true
            column: discipline_id
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            nullable: true
            length: 200
    manyToOne:
        owningSchool:
            targetEntity: School    
            joinColumns:
                owning_school_id:
                    referencedColumnName: school_id
    manyToMany:
        courses:
            targetEntity: Course
            mappedBy: disciplines
        programYears:
            targetEntity: ProgramYear
            mappedBy: disciplines
        sessions:
            targetEntity: Session
            mappedBy: disciplines
