Ilios\CoreBundle\Entity\LearningMaterialUserRole:
    type: entity
    table: learning_material_user_role
    id:
        learningMaterialUserRoleId:
            type: integer
            unsigned: true
            id: true
            column: learning_material_user_role_id    
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 60
    oneToMany:
        learningMaterials:
            targetEntity: LearningMaterial
            mappedBy: userRole
