Ilios\CoreBundle\Entity\MeshTerm:
    type: entity
    table: mesh_term
    id:
        meshTermUid:
            type: string
            length: 9
            id: true
            column: mesh_term_uid
            generator:
                strategy: NONE
        name:
            type: string
            id: true
            length: 192
            generator:
                strategy: NONE
    fields:
        lexicalTag:
            type: string
            nullable: true
            length: 12
            column: lexical_tag
        conceptPreferred:
            type: boolean
            nullable: true
            column: concept_preferred
        recordPreferred:
            type: boolean
            nullable: true
            column: record_preferred
        permuted:
            type: boolean
            nullable: true
        print:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
