Ilios\CoreBundle\Entity\MeshQualifier:
    type: entity
    table: mesh_qualifier
    id:
        meshQualifierUid:
            type: string
            length: 9
            id: true
            column: mesh_qualifier_uid
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 60
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
