Ilios\CoreBundle\Entity\MeshConceptXTerm:
    type: entity
    table: mesh_concept_x_term
    indexes:
        mesh_concept_uid:
            columns:
                - mesh_concept_uid
        mesh_term_uid:
            columns:
                - mesh_term_uid
    id:
        meshConceptUid:
            type: string
            length: 9
            id: true
            column: mesh_concept_uid
        meshTermUid:
            type: string
            length: 9
            id: true
            column: mesh_term_uid    
