Ilios\CoreBundle\Entity\MeshTreeXDescriptor:
    type: entity
    table: mesh_tree_x_descriptor
    id:
        treeNumber:
            type: string
            length: 31
            id: true
            column: tree_number    
            generator:
                strategy: NONE
    fields:
        meshDescriptorUid:
            type: string
            length: 9
            column: mesh_descriptor_uid
