Ilios\CoreBundle\Entity\MeshConcept:
    type: entity
    table: mesh_concept
    id:
        meshConceptUid:
            type: string
            length: 9
            id: true
            column: mesh_concept_uid    
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 192
        umlsUid:
            type: string
            length: 9
            column: umls_uid
        preferred:
            type: boolean
        scopeNote:
            type: text
            nullable: true
            column: scope_note
        casn1Name:
            type: string
            nullable: true
            length: 127
            column: casn_1_name
        registryNumber:
            type: string
            nullable: true
            length: 30
            column: registry_number
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
