Ilios\CoreBundle\Entity\Objective:
    type: entity
    table: objective
    indexes:
        fkey_objective_competency:
            columns:
                - competency_id
    id:
        objectiveId:
            type: integer
            unsigned: true
            id: true
            column: objective_id   
            generator: { strategy: AUTO } 
    fields:
        title:
            type: text
    manyToOne:
        competency:
            targetEntity: Competency
            joinColumns:
                competency_id:
                    referencedColumnName: competency_id
    manyToMany:
        courses:
            targetEntity: Course
            mappedBy: objectives
        programYears:
            targetEntity: ProgramYear
            mappedBy: objectives
        sessions:
            targetEntity: Session
            mappedBy: objectives
        children:
            targetEntity: Objective
            mappedBy: parents
#        meshDescriptors:
#            targetEntity: MeshDescriptor
#            inversedBy: objectives
#            joinTable:
#                name: objective_x_mesh
#                joinColumns:
#                    objective_id:
#                        referencedColumnName: objective_id
#                inverseJoinColumns:
#                    mesh_descriptor_uid:
#                        referencedColumnName: mesh_descriptor_uid
        parents:
            targetEntity: Objective
            inversedBy: children
            joinTable:
                name: objective_x_objective
                joinColumns:
                    objective_id:
                        referencedColumnName: objective_id
                inverseJoinColumns:
                    parent_objective_id:
                        referencedColumnName: objective_id
