Ilios\CoreBundle\Entity\PublishEvent:
    type: entity
    table: publish_event
    id:
        publishEventId:
            type: integer
            unsigned: true
            id: true
            column: publish_event_id    
            generator: { strategy: AUTO }
    fields:
        machineIp:
            type: string
            length: 15
            column: machine_ip
        timeStamp:
            type: datetime
            default: CURRENT_TIMESTAMP
            column: time_stamp
        tableName:
            type: string
            length: 30
            column: table_name
        tableRowId:
            type: integer
            unsigned: true
            column: table_row_id
    manyToOne:
        administrator:
            targetEntity: User
            inversedBy: publishEvents
            joinColumns:
                administrator_id:
                    referencedColumnName: user_id
