Ilios\CoreBundle\Entity\School:
    type: entity
    table: school
    uniqueConstraints:
        template_prefix:
            columns:
                - template_prefix
    id:
        schoolId:
            type: integer
            unsigned: true
            id: true
            column: school_id    
            generator: { strategy: AUTO }
    fields:
        templatePrefix:
            type: string
            nullable: true
            length: 8
            column: template_prefix
        title:
            type: string
            length: 60
        iliosAdministratorEmail:
            type: string
            length: 100
            column: ilios_administrator_email
        deleted:
            type: boolean
        changeAlertRecipients:
            type: text
            nullable: true
            column: change_alert_recipients
    manyToMany:
        alerts:
            targetEntity: Alert
            mappedBy: recipients
