Ilios\CoreBundle\Entity\SessionLearningMaterial:
    type: entity
    table: session_learning_material
    indexes:
        session_lm_k:
            columns:
                - session_id
                - learning_material_id
        learning_material_id_k:
            columns:
                - learning_material_id
        IDX_9BE2AF8D613FECDF:
            columns:
                - session_id
    id:
        sessionLearningMaterialId:
            type: integer
            unsigned: true
            id: true
            column: session_learning_material_id    
            generator: { strategy: AUTO }
    fields:
        notes:
            type: text
            nullable: true
        required:
            type: boolean
        notesArePublic:
            type: boolean
            column: notes_are_public
    manyToOne:
        session:
            targetEntity: Session    
            joinColumns:
                session_id:
                    referencedColumnName: session_id    
        learningMaterial:
            targetEntity: LearningMaterial    
            joinColumns:
                learning_material_id:
                    referencedColumnName: learning_material_id    
#    manyToMany:
#        meshDescriptors:
#            targetEntity: MeshDescriptor
#            inversedBy: sessionLearningMaterials
#            joinTable:
#                name: session_learning_material_x_mesh
#                joinColumns:
#                    session_learning_material_id:
#                        referencedColumnName: session_learning_material_id
#                inverseJoinColumns:
#                    mesh_descriptor_uid:
#                        referencedColumnName: mesh_descriptor_uid    
    
