Ilios\CoreBundle\Entity\SessionDescription:
    type: entity
    table: session_description
    id:
        sessionId:
            type: integer
            unsigned: true
            id: true
            column: session_id
            generator:
                strategy: NONE
    fields:
        description:
            type: text
    oneToOne:
        session:
            targetEntity: Session
            joinColumns:
                session_id:
                    referencedColumnName: session_id    
