Ilios\CoreBundle\Entity\UserMadeReminder:
    type: entity
    table: user_made_reminder
    indexes:
        due_closed_user_k:
            columns:
                - due_date
                - closed
                - user_id
    id:
        userMadeReminderId:
            type: integer
            unsigned: true
            id: true
            column: user_made_reminder_id    
            generator: { strategy: AUTO }
    fields:
        note:
            type: string
            length: 150
        creationDate:
            type: datetime
            column: creation_date
        dueDate:
            type: datetime
            column: due_date
        closed:
            type: boolean
    manyToOne:
        user:
            targetEntity: User
            inversedBy: reminders
            joinColumns:
                user_id:
                    referencedColumnName: user_id   
