#!/bin/sh
# started with https://github.com/docker-library/php/blob/d97098c8c6af46ae1211e65ff052278ab39ba45c/7.2/stretch/apache/docker-php-entrypoint
set -e

# We need to warmup the cache in addition to starting apache
sudo -E -u www-data /var/www/ilios/bin/console cache:warmup

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
