#!/bin/sh
set -e

/srv/app/bin/console cache:warmup
/bin/chown -R www-data:www-data /srv/app

# From https://github.com/docker-library/php/blob/cf8840d0d56ef92e899dac67ebdf8112e9d2f492/8.0/alpine3.13/fpm/docker-php-entrypoint
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
