<?php

namespace Ilios\CoreBundle\Tests\DataLoader;

class SessionData extends AbstractDataLoader
{
    protected function getData()
    {
        $arr = array();

        $arr[] = array(
            'id' => 16468,
            'title' => "Case 1",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "122",
            'course' => "595",
            'disciplines' => ['16'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58417",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16469,
            'title' => "Introduction to Prologue",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58466",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16470,
            'title' => "Introduction to Anatomy and Embryology ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','15','163'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58456",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16471,
            'title' => "Cells & Tissues",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['8'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58422",
            'learningMaterials' => [
                '47172',
                '47208',
                '49240',
                '49241',
                '49252',
                '49253',
                '49254',
                '49255',
                '49256',
                '49257',
                '49359',
                '49360',
            ],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16472,
            'title' => "Introduction to MSP ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58461",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16473,
            'title' => "Introduction to Pharmacology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58465",
            'learningMaterials' => [
                '47394',
                '47395',
                '47396',
                '47397',
                '49523',
                '49524',
                '49531',
                '49532',
                '49553',
                '49554',
            ],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16474,
            'title' => "Epithelia",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58430",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16475,
            'title' => "Histo Lab 1: Cell Structure",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58440",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16476,
            'title' => "Circulatory & Respiratory Systems",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58421",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16477,
            'title' => "Extracellular Matrix and Connective Tissue: Assembly of Cells into Tissues",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58435",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16478,
            'title' => "Introduction to Radiology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['57'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58467",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16479,
            'title' => "Histo Lab 2: Epithelia & Connective Tissue",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58441",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16480,
            'title' => "Diffusion & Transport Across Cell Membranes",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:16+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['5'],
            'objectives' => [
                '76444',
                '76445',
                '76446',
                '76447',
                '76448',
                '76449',
                '76450',
                '76451',
                '76452',
                '76453',
                '76454',
                '76455',
                '76456',
                '76457',
            ],
            'meshDescriptors' => [
                'D000254',
                'D001812',
                'D004058',
                'D005057',
                'D007473',
                'D008565',
                'D008566',
                'D010599',
                'D011506',
                'D011978',
                'D017920',
                'D018528',
                'D020168',
                'D027981',
            ],
            'publishEvent' => "58425",
            'learningMaterials' => [
                '47355',
                '47360',
                '47361',
                '49244',
                '49245',
                '49281',
                '49397',
                '49398',
                '49399',
                '49403',
            ],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16481,
            'title' => "OPTIONAL: An Introduction Emergency Medicine: Basic First Aid and CPR",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-11T12:05:05+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16482,
            'title' => "Pharmacology and Biochemistry Small Group Discussion 1",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['5','8','50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58497",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => [
                '46117',
                '46118',
                '46119',
                '46120',
                '46121',
                '46122',
                '46123',
                '46124',
                '46125',
                '46126',
                '46127',
                '46128',
            ]
        );

        $arr[] = array(
            'id' => 16483,
            'title' => "Nervous System 1: Histology (ONLINE LECTURE-view before Thursday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','166'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58477",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16484,
            'title' => "Muscles",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58475",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16485,
            'title' => "Histo Lab 3: Nerves & Muscles",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58442",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16486,
            'title' => "Protein Structure & Function",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['5'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58503",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16487,
            'title' => "Case 2: The Secondary Survey",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "122",
            'course' => "595",
            'disciplines' => ['16'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58418",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16488,
            'title' => "Autonomic Nervous System Physiology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['37','51'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58408",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16489,
            'title' => "Quantification of Pharmacodynamic Effects",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58504",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16490,
            'title' => "Nervous System 2: Spinal Cord and Peripheral Nerves (ONLINE LECTURE-view before Thursday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','166'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58478",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16491,
            'title' => "Autonomic Nervous System Physiology & Pharmacology: Cholinomimetics and Cholinergic Antagonists (ONLINE LECTURE-view before Tuesday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['37','50','51'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58409",
            'learningMaterials' => [
                '47200',
                '49274',
                '49548',
                '49549',
                '49550',
                '49551',
                '49636',
                '49637',
                '49638',
                '49639',
            ],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16492,
            'title' => "Anatomy Lab 1: Introduction to the Body",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58391",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16493,
            'title' => "Pharmacology and Biochemistry Small Group Discussion 2",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58521",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16494,
            'title' => "Biopsychosocial Model in Medicine: An Introduction to the Social and Behavioral Determinants of Health (SBS)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['4','158'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58531",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16495,
            'title' => "Genetic Variation and Human Disease",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['21'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58526",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16496,
            'title' => "Thorax & Anterior Abdominal Walls",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58515",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16497,
            'title' => "Anatomy Lab 3: Back and Spinal Cord",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58394",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16498,
            'title' => "Mendelian Inheritance",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => ['21'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58528",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16499,
            'title' => "Principles of Cytogenetics",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['21'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58530",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16500,
            'title' => "Anatomy Lab 4: Shoulder",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58522",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16501,
            'title' => "Surface Anatomy: Neck Thorax and Abdomen",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58512",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16502,
            'title' => "Blood Cells",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58523",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16503,
            'title' => "Blood Vessels (Online Lecture-due by Histo Lab 4)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58524",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16504,
            'title' => "Open Lab & View Practice Practical Questions",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58490",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16505,
            'title' => "Histo Lab 4: Blood Cells and Blood Vessels",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['25'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58525",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16506,
            'title' => "Non-Traditional Inheritance",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-27T09:54:31+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16507,
            'title' => "Inheritance of Genetic Disorders",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['21'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59675",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16509,
            'title' => "Anatomy Lab 5: Anterior Forearm and Palmar Hand",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58529",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16510,
            'title' => "Reading Day ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:33+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58506",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16511,
            'title' => "Written Exam I",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "137",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58517",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16512,
            'title' => "Hip, Thigh and Knee",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58439",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16513,
            'title' => "Leg & Foot",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58468",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16514,
            'title' => "Introduction to  Clinical Ethics",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['19','53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58455",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16515,
            'title' => "Pharmacokinetics I",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59673",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16516,
            'title' => "Biases In Medicine",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => ['4','13','158','159'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58532",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16517,
            'title' => "Panel Discussion: Biases in Medicine",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "122",
            'course' => "595",
            'disciplines' => ['4','13','158','159'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58533",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16519,
            'title' => "Pharmacokinetics 2 ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['50'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59676",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16522,
            'title' => "Case 3: The Intensive Care Unit",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "122",
            'course' => "595",
            'disciplines' => ['16'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58535",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16523,
            'title' => "Biases in Medicine Small Group ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['4','13','158','159'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59677",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => [
                '46220',
                '46221',
                '46222',
                '46223',
                '46224',
                '46225',
                '46226',
                '46227',
                '46228',
                '46229',
                '46230',
                '46231',
                '53076',
                '53089',
                '53090',
            ]
        );

        $arr[] = array(
            'id' => 16524,
            'title' => "Introduction to Pathology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['48'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59680",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16526,
            'title' => "Introduction to Cell Injury: Cell Death and Adaptations",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['8','48'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59682",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16528,
            'title' => "Anatomy Lab 2: Neck",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:09+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [
                '76770',
                '76771',
                '76772',
                '76773',
                '76774',
                '76775',
                '76776',
                '76777',
                '76778',
                '76779',
                '76780',
                '76781',
                '76782',
                '76783',
                '85487',
                '85488',
            ],
            'meshDescriptors' => ['D002339','D009333'],
            'publishEvent' => "58392",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16533,
            'title' => "Anatomy Lab 6: Posterior Forearm and Dorsal Hand ",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58537",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16534,
            'title' => "Health Policy: Health Care's Backstory",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['4','160','162'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58438",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16535,
            'title' => "Introduction to Neoplasia (ONLINE LECTURE-view before Lab Thursday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['48'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58462",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16538,
            'title' => "Mr. Danovic's Outpatient Care Interview",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "122",
            'course' => "595",
            'disciplines' => ['4','150','158'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58474",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16540,
            'title' => "Anatomy Lab 7: Anterior and Medial Thigh, and Anterior Leg",
            'attireRequired' => true,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:11+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => ['2','10','150'],
            'objectives' => [
                '76851',
                '76852',
                '76853',
                '76854',
                '76855',
                '76856',
                '76857',
                '76858',
                '76859',
                '76860',
                '76861',
                '76862',
                '85497',
                '85498',
            ],
            'meshDescriptors' => ['D000715','D005269','D013848','D052097'],
            'publishEvent' => "58403",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16541,
            'title' => "Team Learning and Communication Skills (TLCS)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59678",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => [
                '46262',
                '46263',
                '46264',
                '46265',
                '46266',
                '46267',
                '46268',
                '46269',
                '46270',
                '46271',
                '46272',
                '46273',
            ]
        );

        $arr[] = array(
            'id' => 16542,
            'title' => "Written Exam II",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:35+00:00",
            'sessionType' => "137",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58518",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16543,
            'title' => "Exam II Practical",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:18+00:00",
            'sessionType' => "148",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58431",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16544,
            'title' => "Signaling",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['5'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58508",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16545,
            'title' => "Early Embryonic Development: Weeks 2 and 3 (Formation of the Basic Body Plan)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','15','163'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58427",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16546,
            'title' => "Introduction to Pharmacogenetics",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['21'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59679",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16547,
            'title' => "Embryology Peer Facilitated Small Groups",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['2','15'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59683",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => [
                '46282',
                '46283',
                '46284',
                '46285',
                '46286',
                '46287',
                '46288',
                '46289',
                '46290',
                '46291',
                '46292',
                '46293',
                '49803',
                '49804',
                '49805',
                '49806',
                '49807',
                '49808',
                '49809',
                '49810',
            ]
        );

        $arr[] = array(
            'id' => 16549,
            'title' => "Exam I Practical  ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:18+00:00",
            'sessionType' => "148",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58436",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16550,
            'title' => "Midpoint Feedback (Focus Group)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "30",
            'course' => "595",
            'disciplines' => ['53'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58473",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16551,
            'title' => "Mechanisms of Development (ONLINE LECTURE-view before Friday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','15','163'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58470",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16552,
            'title' => "Shoulder",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58507",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16553,
            'title' => "Neck",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58476",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16554,
            'title' => "Radiology of the Shoulder",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['57'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58520",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16555,
            'title' => "Arm, Forearm and Hand",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:33:33+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2'],
            'objectives' => [
                '76922',
                '76923',
                '76924',
                '76925',
                '76926',
                '76927',
                '76928',
                '76929',
                '76930',
                '76931',
                '76932',
                '76933',
                '76934',
                '76935',
                '76936',
            ],
            'meshDescriptors' => ['D001132'],
            'publishEvent' => "58527",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16556,
            'title' => "Development of the Musculoskeletal and Integumentary Systems",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => ['2','15'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "59674",
            'learningMaterials' => [
                '47239',
                '47240',
                '47241',
                '47242',
                '47243',
                '50711',
                '50712',
                '50758',
                '50760',
                '51107',
            ],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16559,
            'title' => "ILM - Anatomical Terminology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-27T08:10:27+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16560,
            'title' => "ILM - Inguinal Hernias",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-27T08:10:58+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16561,
            'title' => "ILM - Diffusion and Transport Worksheet (Due by Tuesday 9/9)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:21+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => ['5'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58446",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16562,
            'title' => "ILM - Genes and Gene Expression",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-27T08:10:52+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16563,
            'title' => "ILM - Population Genetics",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-27T08:14:42+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16564,
            'title' => "ILM - Pharmacokinetics III: Drug Metabolism",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-08-11T11:59:06+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16567,
            'title' => "Competencies, Milestones & Self-Directed Assessment Seeking ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58423",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16569,
            'title' => "Immunology Q&A (Optional) ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => true,
            'updatedAt' => "2014-04-24T14:56:42+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16571,
            'title' => "Exam I Viewing  ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58432",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16572,
            'title' => "IPE Day 1 ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "28",
            'course' => "595",
            'disciplines' => ['151'],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58451",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16573,
            'title' => "Open Book Exam I (Due by Thursday 9/25)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:29+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58489",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16574,
            'title' => "Open Book Exam 2 (Due by Thursday 10/23)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:29+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58488",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16575,
            'title' => "Exam II Viewing ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58433",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16576,
            'title' => "Office Hours Biochem/Pharmacology",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:28+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58484",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16577,
            'title' => "ILM - Ocular Effects of ANS Pharmacology  (Ophthalmology) (Due by Thursday 9/25)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58447",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16578,
            'title' => "MSP (Medical Scholars Program) Tutoring Sessions",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:25+00:00",
            'sessionType' => "125",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58469",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => [
                '46356',
                '46357',
                '46358',
                '46359',
                '46360',
                '46361',
                '46362',
                '46363',
                '46364',
                '46365',
                '46366',
                '46367',
                '46368',
                '46369',
                '46370',
                '46371',
                '46372',
                '46373',
                '46374',
                '46375',
                '46376',
                '46377',
                '46378',
                '46379',
                '46380',
                '46381',
                '46382',
                '46383',
                '54599',
            ]
        );

        $arr[] = array(
            'id' => 16579,
            'title' => "ILM-Radiology: Ultrasound Module (Due by Lab 1[A&B students]; Lab 2 [C&D students]; Lab 3 [E&F students])",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:22+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58450",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16580,
            'title' => "ILM-Dermatology Module (Due by Monday 9/15)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:22+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58449",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16581,
            'title' => "Anatomy Lab Closed ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-04-22T11:47:10+00:00",
            'sessionType' => "23",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 16582,
            'title' => "Office Hours: Genetics-Dr. Hyland ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:28+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58486",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17304,
            'title' => "Embryology Q&A-Dr. Donjacour ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:17+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58429",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17386,
            'title' => "Pharmacokinetics 3: Drug Metabolism (ONLINE LECTURE-view before Wednesday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58494",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17387,
            'title' => "Neoplasia (ONLINE LECTURE)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => true,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-06-03T16:07:14+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17389,
            'title' => "Primary Care Summit (OPTIONAL)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:31+00:00",
            'sessionType' => "112",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58500",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17547,
            'title' => "EC & Kaiser Teaching Awards Ceremony ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:16+00:00",
            'sessionType' => "110",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58426",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17548,
            'title' => "Non-Traditional Inheritance (ONLINE LECTURE-view before Friday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58481",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17549,
            'title' => "Anatomy Lab 1 VIDEO: Introduction to the Body",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:09+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58386",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17550,
            'title' => "Anatomy Lab 3 VIDEO : Back and Spinal Cord",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:09+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58393",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17551,
            'title' => "Anatomy Lab 2 VIDEO: Neck",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:09+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58388",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17552,
            'title' => "Anatomy Lab 4 VIDEO: Shoulder",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:10+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58395",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17553,
            'title' => "Anatomy Lab 5 VIDEO: Anterior Forearm and Palmar Hand",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:10+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58397",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17555,
            'title' => "Anatomy Lab 6 VIDEO: Posterior Forearm and Dorsal Hand ",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:11+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58399",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17556,
            'title' => "Anatomy Lab 7 VIDEO: Anterior and Medial Thigh, and Anterior Leg",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:11+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58401",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17557,
            'title' => "Anatomy Lab 8 VIDEO: Gluteal Region, Posterior Thigh, and Posterior Leg",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:11+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58402",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 17558,
            'title' => "Anatomy Lab 9 VIDEO: Hip, Knee, Ankle",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:11+00:00",
            'sessionType' => "129",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58405",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 18588,
            'title' => "Nervous System 3: Vertebral Column and Muscles of the Back (ONLINE LECTURE-view before Thursday)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58479",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 18630,
            'title' => "Nervous System 4: Large Group Discussion",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58480",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 18631,
            'title' => "Non-Traditional Inheritance Large Group Activity",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2015-06-14T11:18:11+00:00",
            'sessionType' => "115",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58534",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 18783,
            'title' => "Office Hours: Anne Donjacour (Embryology)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:28+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58485",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19060,
            'title' => "ILM- Hernia (Due by Wednesday, 9/10)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:21+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58448",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19543,
            'title' => "Genes, Genomes, and Gene Expressions (Due by Sept 30)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:18+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58434",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19544,
            'title' => "Mendelian Inheritance (Due by Oct 1)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:26+00:00",
            'sessionType' => "19",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58472",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19569,
            'title' => "Non-Traditional Inheritance (Online Lecture-Due by Oct 3rd)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => false,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:28+00:00",
            'sessionType' => "25",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58482",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19578,
            'title' => "Office Hours: Histology Lab",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:29+00:00",
            'sessionType' => "26",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58487",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );

        $arr[] = array(
            'id' => 19594,
            'title' => "Prologue Course Celebration (Please attend)",
            'attireRequired' => false,
            'equipmentRequired' => false,
            'supplemental' => true,
            'deleted' => false,
            'publishedAsTbd' => false,
            'updatedAt' => "2014-10-30T14:23:32+00:00",
            'sessionType' => "145",
            'course' => "595",
            'disciplines' => [],
            'objectives' => [],
            'meshDescriptors' => [],
            'publishEvent' => "58502",
            'learningMaterials' => [],
            'instructionHours' => [],
            'offerings' => []
        );


        return $arr;
    }

    public function create()
    {
        return [];
    }

    public function createInvalid()
    {
        return [];
    }
}
