Term:
 type: object
 properties:
  id:
   description: Id
   type: integer
   readOnly: true
  courses:
   description: Courses
   type: array
   items:
    type: string
  description:
   description: Description
   type: string
  parent:
   description: Parent
   type: string
  children:
   description: Children
   type: array
   items:
    type: string
  programYears:
   description: Programyears
   type: array
   items:
    type: string
  sessions:
   description: Sessions
   type: array
   items:
    type: string
  title:
   description: Title
   type: string
  vocabulary:
   description: Vocabulary
   type: string
  aamcResourceTypes:
   description: Aamcresourcetypes
   type: array
   items:
    type: string
  active:
   description: Active
   type: boolean
  objectives:
   description: Objectives
   type: array
   items:
    type: string
