<?php

declare(strict_types=1);

namespace App\Tests\DataLoader;

use App\Entity\DTO\UserDTO;

class UserData extends AbstractDataLoader
{
    public const int ROOT_USER_ID = 2;

    protected function getData(): array
    {
        $arr = [];

        $arr[] = [
            'id' => 1,
            'lastName' => 'last',
            'firstName' => 'erster',
            'middleName' => 'middle',
            'displayName' => 'something else',
            'email' => 'erster@test.org',
            'preferredEmail' => 'something.else@test.org',
            'pronouns' => 'he/she/they',
            'phone' => '111-111-1111',
            'enabled' => true,
            'campusId' => '1111@school.edu',
            'userSyncIgnore' => false,
            'addedViaIlios' => false,
            'examined' => true,
            'root' => false,
            'icsFeedKey' => hash('sha256', '1'),
            'reports' => [],
            'school' => 1,
            'authentication' => 1,
            'primaryCohort' => 1,
            'directedCourses' => ['1'],
            'learnerGroups' => [],
            'instructedLearnerGroups' => ['1', '3'],
            'instructorGroups' => [],
            'instructorIlmSessions' => [],
            'learnerIlmSessions' => [],
            'offerings' => [],
            'instructedOfferings' => ["6", "8"],
            'programYears' => ['1'],
            'roles' => ['1'],
            'cohorts' => ['1'],
            'pendingUserUpdates' => ['1'],
            'directedSchools' => ['1'],
            'administeredSchools' => ['1'],
            'administeredSessions' => ['1'],
            'administeredCourses' => ['1'],
            'studentAdvisedCourses' => [],
            'studentAdvisedSessions' => [],
            'directedPrograms' => ['1'],
            'administeredCurriculumInventoryReports' => ['1'],
            'sessionMaterialStatuses' => [],
        ];

        $arr[] = [
            'id' => self::ROOT_USER_ID,
            'lastName' => 'first',
            'middleName' => 'first',
            'firstName' => 'first',
            'displayName' => 'disnom',
            'email' => 'first@example.com',
            'preferredEmail' => 'last@test.com',
            'pronouns' => 'them',
            'phone' => '415-555-0123',
            'enabled' => true,
            'campusId' => '2222@school.edu',
            'userSyncIgnore' => true,
            'addedViaIlios' => true,
            'examined' => true,
            'icsFeedKey' => hash('sha256', '2'),
            'root' => true,
            'reports' => ['1', '2', '3'],
            'school' => 1,
            'authentication' => 2,
            'directedCourses' => ['2', '4'],
            'learnerGroups' => ['1', '2', '3'],
            'instructedLearnerGroups' => [],
            'instructorGroups' => ['1', '2', '3'],
            'instructorIlmSessions' => ['3'],
            'learnerIlmSessions' => ['4'],
            'offerings' => ['4'],
            'instructedOfferings' => ['5'],
            'programYears' => [],
            'roles' => ['1'],
            'cohorts' => ['1'],
            'pendingUserUpdates' => [],
            'directedSchools' => [],
            'administeredSchools' => [],
            'administeredSessions' => [],
            'administeredCourses' => [],
            'studentAdvisedCourses' => ['1'],
            'studentAdvisedSessions' => [],
            'directedPrograms' => [],
            'administeredCurriculumInventoryReports' => [],
            'sessionMaterialStatuses' => ['1', '2', '3'],
            'primaryCohort' => null,
        ];

        $arr[] = [
            'id' => 3,
            'lastName' => 'second',
            'middleName' => 'lorem',
            'firstName' => 'second',
            'email' => 'second@example.com',
            'preferredEmail' => 'zweite@example.de',
            'pronouns' => '',
            'phone' => '222-222-9999',
            'enabled' => true,
            'campusId' => '3333@school.edu',
            'otherId' => '001',
            'userSyncIgnore' => false,
            'addedViaIlios' => false,
            'examined' => false,
            'icsFeedKey' => hash('sha256', '3'),
            'root' => false,
            'reports' => [],
            'school' => 1,
            'authentication' => 3,
            'directedCourses' => [],
            'learnerGroups' => [],
            'instructedLearnerGroups' => [],
            'instructorGroups' => [],
            'instructorIlmSessions' => [],
            'learnerIlmSessions' => [],
            'offerings' => [],
            'instructedOfferings' => [],
            'programYears' => [],
            'roles' => ['2'],
            'cohorts' => [],
            'pendingUserUpdates' => [],
            'directedSchools' => [],
            'administeredSchools' => [],
            'administeredSessions' => [],
            'administeredCourses' => [],
            'studentAdvisedCourses' => ['3'],
            'studentAdvisedSessions' => ['4'],
            'directedPrograms' => [],
            'administeredCurriculumInventoryReports' => [],
            'sessionMaterialStatuses' => [],
            'primaryCohort' => null,
        ];

        $arr[] = [
            'id' => 4,
            'lastName' => 'four',
            'middleName' => 'vier',
            'firstName' => 'quadro',
            'displayName' => 'ipsum',
            'email' => 'four@test.org',
            'preferredEmail' => 'ipsum@test.org',
            'phone' => '888-999-0999',
            'enabled' => true,
            'campusId' => '4444@school.edu',
            'userSyncIgnore' => false,
            'addedViaIlios' => false,
            'examined' => false,
            'icsFeedKey' => hash('sha256', '4'),
            'root' => false,
            'reports' => [],
            'school' => "2",
            'directedCourses' => ["3"],
            'learnerGroups' => [],
            'instructedLearnerGroups' => [],
            'instructorGroups' => ['2'],
            'instructorIlmSessions' => [],
            'learnerIlmSessions' => [],
            'offerings' => [],
            'instructedOfferings' => [],
            'programYears' => [],
            'roles' => [],
            'cohorts' => [],
            'pendingUserUpdates' => ['2'],
            'directedSchools' => [],
            'administeredSchools' => [],
            'administeredSessions' => [],
            'administeredCourses' => ['5'],
            'studentAdvisedCourses' => [],
            'studentAdvisedSessions' => [],
            'directedPrograms' => [],
            'administeredCurriculumInventoryReports' => [],
            'sessionMaterialStatuses' => [],
            'primaryCohort' => null,
            'authentication' => null,
        ];

        $arr[] = [
            'id' => 5,
            'lastName' => 'fuenf',
            'middleName' =>  'baz',
            'firstName' => 'five',
            'email' => 'five@test.org',
            'preferredEmail' => 'baz@test.org',
            'phone' => '555-333-3333',
            'enabled' => true,
            'campusId' => '5555@school.edu',
            'userSyncIgnore' => false,
            'addedViaIlios' => false,
            'examined' => false,
            'icsFeedKey' => hash('sha256', '5'),
            'root' => false,
            'reports' => [],
            'school' => "1",
            'directedCourses' => [],
            'learnerGroups' => ['1', '5'],
            'instructedLearnerGroups' => [],
            'instructorGroups' => [],
            'instructorIlmSessions' => [],
            'learnerIlmSessions' => [],
            'offerings' => ['7'],
            'instructedOfferings' => [],
            'programYears' => [],
            'roles' => [],
            'cohorts' => [],
            'pendingUserUpdates' => [],
            'directedSchools' => [],
            'administeredSchools' => [],
            'administeredSessions' => [],
            'administeredCourses' => [],
            'studentAdvisedCourses' => [],
            'studentAdvisedSessions' => [],
            'directedPrograms' => [],
            'administeredCurriculumInventoryReports' => [],
            'sessionMaterialStatuses' => [],
            'primaryCohort' => null,
            'authentication' => null,
        ];

        return $arr;
    }

    public function create(): array
    {
        return [
            'id' => 6,
            'lastName' => 'six',
            'firstName' => 'sechs',
            'middleName' => 'middle',
            'email' => 'sechs@test.org',
            'preferredEmail' => 'six@test.org',
            'phone' => '400-400-0000',
            'enabled' => true,
            'campusId' => '5555@school.edu',
            'userSyncIgnore' => false,
            'addedViaIlios' => true,
            'examined' => false,
            'icsFeedKey' => hash('sha256', microtime()),
            'root' => false,
            'reports' => [],
            'school' => "1",
            'directedCourses' => ['1'],
            'learnerGroups' => ['1'],
            'instructedLearnerGroups' => ['1'],
            'instructorGroups' => ['1'],
            'instructorIlmSessions' => ['1'],
            'learnerIlmSessions' => ['1'],
            'offerings' => ['1'],
            'instructedOfferings' => ['1'],
            'programYears' => ['1'],
            'roles' => ['1'],
            'cohorts' => ['1'],
            'pendingUserUpdates' => [],
            'directedSchools' => [],
            'administeredSchools' => [],
            'administeredSessions' => [],
            'administeredCourses' => [],
            'studentAdvisedCourses' => [],
            'studentAdvisedSessions' => [],
            'directedPrograms' => [],
            'administeredCurriculumInventoryReports' => [],
            'sessionMaterialStatuses' => [],
            'primaryCohort' => null,
            'authentication' => null,

        ];
    }

    public function createEmpty(): array
    {
        return [
            'lastName' => 'new',
            'firstName' => 'user',
            'email' => 'new.user@test.org',
            'school' => "1",
        ];
    }

    public function createInvalid(): array
    {
        return [];
    }

    public function getDtoClass(): string
    {
        return UserDTO::class;
    }
}
