LOCK TABLES `curriculum_inventory_institution` WRITE;
/*!40000 ALTER TABLE `curriculum_inventory_institution` DISABLE KEYS */;
INSERT INTO `curriculum_inventory_institution` (`school_id`, `name`, `aamc_code`, `address_street`, `address_city`, `address_state_or_province`, `address_zipcode`, `address_country_code`) VALUES (1, 'School of Medicine', '00000', '', '', '', '', '');
INSERT INTO `curriculum_inventory_institution` (`school_id`, `name`, `aamc_code`, `address_street`, `address_city`, `address_state_or_province`, `address_zipcode`, `address_country_code`) VALUES (2, 'School of Dentistry', '00000', '', '', '', '', '');
INSERT INTO `curriculum_inventory_institution` (`school_id`, `name`, `aamc_code`, `address_street`, `address_city`, `address_state_or_province`, `address_zipcode`, `address_country_code`) VALUES (3, 'School of Pharmacy', '00000', '', '', '', '', '');
INSERT INTO `curriculum_inventory_institution` (`school_id`, `name`, `aamc_code`, `address_street`, `address_city`, `address_state_or_province`, `address_zipcode`, `address_country_code`) VALUES (4, 'School of Nursing', '00000', '', '', '', '', '');
INSERT INTO `curriculum_inventory_institution` (`school_id`, `name`, `aamc_code`, `address_street`, `address_city`, `address_state_or_province`, `address_zipcode`, `address_country_code`) VALUES (5, 'Other', '00000', '', '', '', '', '');
/*!40000 ALTER TABLE `curriculum_inventory_institution` ENABLE KEYS */;
UNLOCK TABLES;


LOCK TABLES `aamc_method` WRITE;
/*!40000 ALTER TABLE `aamc_method` DISABLE KEYS */;
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM001', 'Case-Based Instruction/Learning');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM002', 'Clinical Experience - Ambulatory');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM003', 'Clinical Experience - Inpatient');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM004', 'Concept Mapping');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM005', 'Conference');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM006', 'Demonstration');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM007', 'Discussion, Large Group (>12)');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM008', 'Discussion, Small Group (≤12)');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM009', 'Games');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM010', 'Independent Learning');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM011', 'Journal Club');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM012', 'Laboratory');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM013', 'Lecture');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM014', 'Mentorship');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM015', 'Patient Presentation - Faculty');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM016', 'Patient Presentation - Learner');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM017', 'Peer Teaching');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM018', 'Preceptorship');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM019', 'Problem-Based Learning (PBL)');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM020', 'Reflection');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM021', 'Research');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM022', 'Role Play/Dramatization');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM023', 'Self-Directed Learning');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM024', 'Service Learning Activity');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM025', 'Simulation');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM026', 'Team-Based Learning (TBL)');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM027', 'Team-Building');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM028', 'Tutorial');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM029', 'Ward Rounds');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('IM030', 'Workshop Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM001', 'Clinical Documentation Review');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM002', 'Clinical Performance Rating/Checklist');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM003', 'Exam - Institutionally Developed, Clinical Performance');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM004', 'Exam - Institutionally Developed, Written/ Computer-based');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM005', 'Exam - Institutionally Developed, Oral');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM006', 'Exam - Licensure, Clinical Performance');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM007', 'Exam - Licensure, Written/Computer-based');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM008', 'Exam - Nationally Normed/Standardized, Subject');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM009', 'Multisource Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM010', 'Narrative Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM011', 'Oral Patient Presentation');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM012', 'Participation');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM013', 'Peer Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM014', 'Portfolio-Based Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM015', 'Practical (Lab)');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM016', 'Research or Project Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM017', 'Self-Assessment');
INSERT INTO `aamc_method` (`method_id`, `description`) VALUES ('AM018', 'Stimulated Recall');
/*!40000 ALTER TABLE `aamc_method` ENABLE KEYS */;
UNLOCK TABLES;
