parameters:
  tdn.type.tdn_entity.class: Ilios\CoreBundle\Form\Type\AbstractType\EntityType
  tdn.type.tdn_many_reated.class: Ilios\CoreBundle\Form\Type\AbstractType\ManyRelatedType
  tdn.type.tdn_single_related.class: Ilios\CoreBundle\Form\Type\AbstractType\SingleRelatedType

services:
  tdn.type.tdn_entity:
    class: %tdn.type.tdn_entity.class%
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: 'form.type', alias: 'tdn_entity' }
  tdn.type.tdn_many_reated:
    class: %tdn.type.tdn_many_reated.class%
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: 'form.type', alias: 'tdn_many_related' }
  tdn.type.tdn_single_related:
    class: %tdn.type.tdn_single_related.class%
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: 'form.type', alias: 'tdn_single_related' }
