parameters:
    ilioscore.dataloader.users.class: Ilios\CoreBundle\Tests\DataLoader\Users
    ilioscore.dataloader.userroles.class: Ilios\CoreBundle\Tests\DataLoader\UserRoles
    ilioscore.dataloader.sessiontypes.class: Ilios\CoreBundle\Tests\DataLoader\SessionTypes
    ilioscore.dataloader.schools.class: Ilios\CoreBundle\Tests\DataLoader\Schools
    ilioscore.dataloader.aamcmethods.class: Ilios\CoreBundle\Tests\DataLoader\AamcMethods
    ilioscore.dataloader.assessmentoptions.class: Ilios\CoreBundle\Tests\DataLoader\AssessmentOptions
    ilioscore.dataloader.cohort.class: NOT_FOUND
    ilioscore.dataloader.learningmaterialstatus.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventoryexport.class: NOT_FOUND
    ilioscore.dataloader.program.class: NOT_FOUND
    ilioscore.dataloader.competency.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventorysequence.class: NOT_FOUND
    ilioscore.dataloader.alertchangetype.class: NOT_FOUND
    ilioscore.dataloader.meshpreviousindexing.class: NOT_FOUND
    ilioscore.dataloader.programyearsteward.class: NOT_FOUND
    ilioscore.dataloader.courseclerkshiptype.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventorysequenceblocksession.class: NOT_FOUND
    ilioscore.dataloader.meshuserselection.class: NOT_FOUND
    ilioscore.dataloader.school.class: NOT_FOUND
    ilioscore.dataloader.session.class: NOT_FOUND
    ilioscore.dataloader.learningmaterialuserrole.class: NOT_FOUND
    ilioscore.dataloader.courselearningmaterial.class: NOT_FOUND
    ilioscore.dataloader.sessionlearningmaterial.class: NOT_FOUND
    ilioscore.dataloader.learningmaterial.class: NOT_FOUND
    ilioscore.dataloader.usermadereminder.class: NOT_FOUND
    ilioscore.dataloader.sessiontype.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventoryacademiclevel.class: NOT_FOUND
    ilioscore.dataloader.objective.class: NOT_FOUND
    ilioscore.dataloader.report.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventoryreport.class: NOT_FOUND
    ilioscore.dataloader.instructionhours.class: NOT_FOUND
    ilioscore.dataloader.ingestionexception.class: NOT_FOUND
    ilioscore.dataloader.department.class: NOT_FOUND
    ilioscore.dataloader.reportpovalue.class: NOT_FOUND
    ilioscore.dataloader.recurringevent.class: NOT_FOUND
    ilioscore.dataloader.instructorgroup.class: NOT_FOUND
    ilioscore.dataloader.meshconcept.class: NOT_FOUND
    ilioscore.dataloader.publishevent.class: NOT_FOUND
    ilioscore.dataloader.aamcpcrs.class: NOT_FOUND
    ilioscore.dataloader.offering.class: NOT_FOUND
    ilioscore.dataloader.aamcmethod.class: NOT_FOUND
    ilioscore.dataloader.meshsemantictype.class: NOT_FOUND
    ilioscore.dataloader.discipline.class: NOT_FOUND
    ilioscore.dataloader.meshqualifier.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventorysequenceblock.class: NOT_FOUND
    ilioscore.dataloader.ilmsessionfacet.class: NOT_FOUND
    ilioscore.dataloader.userrole.class: NOT_FOUND
    ilioscore.dataloader.curriculuminventoryinstitution.class: NOT_FOUND
    ilioscore.dataloader.course.class: NOT_FOUND
    ilioscore.dataloader.meshdescriptor.class: NOT_FOUND
    ilioscore.dataloader.alert.class: NOT_FOUND
    ilioscore.dataloader.programyear.class: NOT_FOUND
    ilioscore.dataloader.learnergroup.class: NOT_FOUND
    ilioscore.dataloader.user.class: NOT_FOUND
    ilioscore.dataloader.sessiondescription.class: NOT_FOUND
    ilioscore.dataloader.assessmentoption.class: NOT_FOUND

services:
    ilioscore.dataloader.users:
        class: %ilioscore.dataloader.users.class%
    ilioscore.dataloader.userroles:
        class: %ilioscore.dataloader.userroles.class%
    ilioscore.dataloader.sessiontypes:
        class: %ilioscore.dataloader.sessiontypes.class%
    ilioscore.dataloader.schools:
        class: %ilioscore.dataloader.schools.class%
    ilioscore.dataloader.aamcmethods:
        class: %ilioscore.dataloader.aamcmethods.class%
    ilioscore.dataloader.assessmentoptions:
        class: %ilioscore.dataloader.assessmentoptions.class%
    ilioscore.dataloader.cohort:
        class: %ilioscore.dataloader.cohort.class%
    ilioscore.dataloader.learningmaterialstatus:
        class: %ilioscore.dataloader.learningmaterialstatus.class%
    ilioscore.dataloader.curriculuminventoryexport:
        class: %ilioscore.dataloader.curriculuminventoryexport.class%
    ilioscore.dataloader.program:
        class: %ilioscore.dataloader.program.class%
    ilioscore.dataloader.competency:
        class: %ilioscore.dataloader.competency.class%
    ilioscore.dataloader.curriculuminventorysequence:
        class: %ilioscore.dataloader.curriculuminventorysequence.class%
    ilioscore.dataloader.alertchangetype:
        class: %ilioscore.dataloader.alertchangetype.class%
    ilioscore.dataloader.meshpreviousindexing:
        class: %ilioscore.dataloader.meshpreviousindexing.class%
    ilioscore.dataloader.programyearsteward:
        class: %ilioscore.dataloader.programyearsteward.class%
    ilioscore.dataloader.courseclerkshiptype:
        class: %ilioscore.dataloader.courseclerkshiptype.class%
    ilioscore.dataloader.curriculuminventorysequenceblocksession:
        class: %ilioscore.dataloader.curriculuminventorysequenceblocksession.class%
    ilioscore.dataloader.meshuserselection:
        class: %ilioscore.dataloader.meshuserselection.class%
    ilioscore.dataloader.school:
        class: %ilioscore.dataloader.school.class%
    ilioscore.dataloader.session:
        class: %ilioscore.dataloader.session.class%
    ilioscore.dataloader.learningmaterialuserrole:
        class: %ilioscore.dataloader.learningmaterialuserrole.class%
    ilioscore.dataloader.courselearningmaterial:
        class: %ilioscore.dataloader.courselearningmaterial.class%
    ilioscore.dataloader.sessionlearningmaterial:
        class: %ilioscore.dataloader.sessionlearningmaterial.class%
    ilioscore.dataloader.learningmaterial:
        class: %ilioscore.dataloader.learningmaterial.class%
    ilioscore.dataloader.usermadereminder:
        class: %ilioscore.dataloader.usermadereminder.class%
    ilioscore.dataloader.sessiontype:
        class: %ilioscore.dataloader.sessiontype.class%
    ilioscore.dataloader.curriculuminventoryacademiclevel:
        class: %ilioscore.dataloader.curriculuminventoryacademiclevel.class%
    ilioscore.dataloader.objective:
        class: %ilioscore.dataloader.objective.class%
    ilioscore.dataloader.report:
        class: %ilioscore.dataloader.report.class%
    ilioscore.dataloader.curriculuminventoryreport:
        class: %ilioscore.dataloader.curriculuminventoryreport.class%
    ilioscore.dataloader.instructionhours:
        class: %ilioscore.dataloader.instructionhours.class%
    ilioscore.dataloader.ingestionexception:
        class: %ilioscore.dataloader.ingestionexception.class%
    ilioscore.dataloader.department:
        class: %ilioscore.dataloader.department.class%
    ilioscore.dataloader.reportpovalue:
        class: %ilioscore.dataloader.reportpovalue.class%
    ilioscore.dataloader.recurringevent:
        class: %ilioscore.dataloader.recurringevent.class%
    ilioscore.dataloader.instructorgroup:
        class: %ilioscore.dataloader.instructorgroup.class%
    ilioscore.dataloader.meshconcept:
        class: %ilioscore.dataloader.meshconcept.class%
    ilioscore.dataloader.publishevent:
        class: %ilioscore.dataloader.publishevent.class%
    ilioscore.dataloader.aamcpcrs:
        class: %ilioscore.dataloader.aamcpcrs.class%
    ilioscore.dataloader.offering:
        class: %ilioscore.dataloader.offering.class%
    ilioscore.dataloader.aamcmethod:
        class: %ilioscore.dataloader.aamcmethod.class%
    ilioscore.dataloader.meshsemantictype:
        class: %ilioscore.dataloader.meshsemantictype.class%
    ilioscore.dataloader.discipline:
        class: %ilioscore.dataloader.discipline.class%
    ilioscore.dataloader.meshqualifier:
        class: %ilioscore.dataloader.meshqualifier.class%
    ilioscore.dataloader.curriculuminventorysequenceblock:
        class: %ilioscore.dataloader.curriculuminventorysequenceblock.class%
    ilioscore.dataloader.ilmsessionfacet:
        class: %ilioscore.dataloader.ilmsessionfacet.class%
    ilioscore.dataloader.userrole:
        class: %ilioscore.dataloader.userrole.class%
    ilioscore.dataloader.curriculuminventoryinstitution:
        class: %ilioscore.dataloader.curriculuminventoryinstitution.class%
    ilioscore.dataloader.course:
        class: %ilioscore.dataloader.course.class%
    ilioscore.dataloader.meshdescriptor:
        class: %ilioscore.dataloader.meshdescriptor.class%
    ilioscore.dataloader.alert:
        class: %ilioscore.dataloader.alert.class%
    ilioscore.dataloader.programyear:
        class: %ilioscore.dataloader.programyear.class%
    ilioscore.dataloader.learnergroup:
        class: %ilioscore.dataloader.learnergroup.class%
    ilioscore.dataloader.user:
        class: %ilioscore.dataloader.user.class%
    ilioscore.dataloader.sessiondescription:
        class: %ilioscore.dataloader.sessiondescription.class%
    ilioscore.dataloader.assessmentoption:
        class: %ilioscore.dataloader.assessmentoption.class%
